---
# https://formulae.brew.sh/cask/firefox
- name: "Firefox | Configuration"
  tags: configure, never
  block:
    - name: "Firefox | Install"
      community.general.homebrew_cask:
        name: firefox
        state: present
