---
- name: "Configure macOS"
  hosts: localhost
  connection: local
  tasks:
    - include_role:
        name: "{{ item }}"
      loop: "{{ default_roles }}"
      tags: always
    - include_role:
        name: "{{ item }}"
      loop: "{{ personal_roles }}"
      tags: personal, never
