---
- name: "Configure macOS"
  hosts: localhost
  connection: local
  tasks:
    - name: "Respawn | General applications"
      include_role:
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      loop: "{{ default_roles }}"
      tags: always
    
    - name: "Respawn | Personal applications"
      include_role:
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      loop: "{{ personal_roles }}"
      tags: personal, never
