---
- name: "System | Configure mouse & trackpad settings"
  tags: configure, never
  block:
    - name: "System | Increase key repeat speed"
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: KeyRepeat
        type: int
        value: 1
        state: present

    - name: "System | Enable tap to click"
      community.general.osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: Clicking
        type: bool
        value: true
        state: present

    - name: "System | Enable global mouse tap to click for currentHost"
      community.general.osx_defaults:
        domain: NSGlobalDomain
        host: currentHost
        key: com.apple.mouse.tapBehavior
        type: int
        value: 1
        state: present

    - name: "System | Enable global mouse tap to click globally"
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.mouse.tapBehavior
        type: int
        value: 1
        state: present
