---
- name: "macOS | Configure personal update settings"
  tags: personal, never
  block:
    - name: "macOS | Enable automatic updates"
      community.general.osx_defaults:
        domain: com.apple.commerce
        key: AutoUpdate
        type: bool
        value: true
        state: present

    - name: "macOS | Enable automatic update check"
      community.general.osx_defaults:
        domain: com.apple.SoftwareUpdate
        key: AutomaticCheckEnabled
        type: bool
        value: true
        state: present

    - name: "macOS | Set updates check to daily"
      community.general.osx_defaults:
        domain: com.apple.SoftwareUpdate
        key: ScheduleFrequency
        type: int
        value: 1
        state: present

    - name: "macOS | Enable downloading updates in the background"
      community.general.osx_defaults:
        domain: com.apple.SoftwareUpdate
        key: AutomaticDownload
        type: int
        value: 1
        state: present

    - name: "macOS | Enable automatic install of critical updates"
      community.general.osx_defaults:
        domain: com.apple.SoftwareUpdate
        key: CriticalUpdateInstall
        type: int
        value: 1
        state: present
