---
- name: Nodenv | Configuration"
  tags: configure, never
  block:
    # https://formulae.brew.sh/formula/nodenv
    - name: "Nodenv | Install"
      community.general.homebrew:
        name: nodenv
        state: present
