---
- name: "Git | Configuration"
  tags: configure, never
  block:
    # https://formulae.brew.sh/formula/git
    - name: "Git | Install"
      community.general.homebrew:
        name: git
        state: present
    
    - name: Git | Synchronize Git config 
      ansible.posix.synchronize:
        src: git/.gitconfig 
        dest: ~/.gitconfig

- name: "Git | Backup Configuration"
  tags: backup, never
  block:
    - name: "Git | Backup Git config to dotfiles repo"
      ansible.posix.synchronize:
        src: ~/.gitconfig 
        dest: git/.gitconfig
