---
# https://formulae.brew.sh/formula/git
- name: "Git | Install"
  community.general.homebrew:
    name: git
    state: present
    
- name: "Git | Configure"
  block:
    - name: Git | Synchronize Git config 
      ansible.posix.synchronize:
        src: git/.gitconfig 
        dest: ~/.gitconfig
