---
- name: "Starship | Configuration"
  tags: configure, never
  block:
    # https://formulae.brew.sh/formula/starship
    - name: "Starship | Install"
      community.general.homebrew:
        name: starship
        state: present

    - name: Starship | Synchronize Starship config 
      ansible.posix.synchronize:
        src: starship/starship.toml 
        dest: ~/.config/starship.toml
