---
# https://formulae.brew.sh/formula/ansible
- name: "Alacritty | Install"
  community.general.homebrew_cask:
    name: alacritty
    state: present

- name: "Alacritty | Configure"
  block:
    - name: Alacritty | Synchronize Alacritty config 
      ansible.posix.synchronize:
        src: alacritty/ 
        dest: ~/.config/alacritty/
        delete: true
        recursive: true
