---
- name: "Neovim | Configuration"
  tags: configure, never
  block:
    # https://formulae.brew.sh/formula/neovim
    - name: "Neovim | Install"
      community.general.homebrew:
        name: neovim
        state: present

    - name: Neovim | Synchronize Neovim config 
      ansible.posix.synchronize:
        src: nvim/ 
        dest: ~/.config/nvim/
        delete: true
        recursive: true
        rsync_opts:
          - "--exclude=*.json"

- name: "Neovim | Backup configuration"
  tags: backup, never
  block:
    - name: Neovim | Backup Neovim config to dotfiles repo"
      ansible.posix.synchronize:
        src: ~/.config/nvim/ 
        dest: nvim/
        delete: true
        recursive: true
        rsync_opts:
          - "--exclude=*.json"
